name: 'iota-sandbox-setup'
description: 'Setup IOTA Sandbox'
runs:
  using: "composite"
  steps:
    - name: Setup iota sandbox
      shell: bash
      run: |
        # Use next lines for using the GitHub release
        mkdir iota-sandbox
        cd iota-sandbox
        mkdir sandbox
        cd sandbox
        # Use the output of https://api.github.com/repos/iotaledger/iota-sandbox/releases/latest
        DOWNLOAD_URL=$(curl "https://api.github.com/repos/iotaledger/iota-sandbox/releases" | jq -r '.[0].assets[] | select(.name | contains("iota_sandbox")) | .browser_download_url')
        echo "Downloading sandbox from $DOWNLOAD_URL"
        curl -L -o iota_sandbox.tar.gz $DOWNLOAD_URL
        tar -xf iota_sandbox.tar.gz

        # Use the next lines to use the main branch
        # git clone https://github.com/iotaledger/iota-sandbox
        # cd iota-sandbox/sandbox

        # Start Tangle
        sudo ./bootstrap.sh
        docker compose --profile inx-faucet up -d
    - name: Wait for tangle to start
      shell: bash
      run: wget -qO- https://raw.githubusercontent.com/eficode/wait-for/$WAIT_FOR_VERSION/wait-for | sh -s -- -t 60 http://localhost/health -- echo "Tangle is up"
      env:
        WAIT_FOR_VERSION: 4df3f9262d84cab0039c07bf861045fbb3c20ab7 # v2.2.3
    - name: Wait for faucet to start
      shell: bash
      run: wget -qO- https://raw.githubusercontent.com/eficode/wait-for/$WAIT_FOR_VERSION/wait-for | sh -s -- -t 60 http://localhost/faucet/api/info -- echo "Faucet is up"
      env:
        WAIT_FOR_VERSION: 4df3f9262d84cab0039c07bf861045fbb3c20ab7 # v2.2.3
