/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export class NapiChainState {
  static fromJSON(jsonValue: any): NapiChainState
  toJSON(): any
}
export class NapiIdentityState {
  static fromJSON(jsonValue: any): NapiIdentityState
  toJSON(): any
}
export class NapiStronghold {
  /**
   * Workaround for Napi not generating code when no factory or constructor is present, and
   * async constructors are not possible.
   */
  static f(): NapiStronghold
  /** Creates an instance of `Stronghold`. */
  static new(snapshot: string, password: string, dropsave?: boolean | undefined | null): Promise<NapiStronghold>
  /** Returns whether save-on-drop is enabled. */
  get dropsave(): boolean
  /**
   * Set whether to save the storage changes on drop.
   * Default: true
   */
  set dropsave(dropsave: boolean)
  /** Sets the account password. */
  setPassword(password: Array<number>): Promise<void>
  /** Write any unsaved changes to disk. */
  flushChanges(): Promise<void>
  /** Creates a new keypair at the specified `location` */
  keyNew(did: NapiDID, location: NapiKeyLocation): Promise<string>
  /** Inserts a private key at the specified `location`. */
  keyInsert(did: NapiDID, location: NapiKeyLocation, privateKey: string): Promise<string>
  /** Retrieves the public key at the specified `location`. */
  keyGet(did: NapiDID, location: NapiKeyLocation): Promise<string>
  /** Deletes the keypair specified by `location`. */
  keyDel(did: NapiDID, location: NapiKeyLocation): Promise<void>
  /** Signs `data` with the private key at the specified `location`. */
  keySign(did: NapiDID, location: NapiKeyLocation, data: Array<number>): Promise<NapiSignature>
  /** Returns `true` if a keypair exists at the specified `location`. */
  keyExists(did: NapiDID, location: NapiKeyLocation): Promise<boolean>
  /** Returns the chain state of the identity specified by `did`. */
  chainState(did: NapiDID): Promise<NapiChainState | undefined | null>
  /** Set the chain state of the identity specified by `did`. */
  setChainState(did: NapiDID, chainState: NapiChainState): Promise<void>
  /** Returns the state of the identity specified by `did`. */
  state(did: NapiDID): Promise<NapiIdentityState | undefined | null>
  /** Sets a new state for the identity specified by `did`. */
  setState(did: NapiDID, state: NapiIdentityState): Promise<void>
  /** Removes the keys and any state for the identity specified by `did`. */
  purge(did: NapiDID): Promise<void>
}
export class NapiKeyLocation {
  static fromJSON(jsonValue: any): NapiKeyLocation
  toJSON(): any
}
export class NapiSignature {
  static fromJSON(jsonValue: any): NapiSignature
  toJSON(): any
}
export class NapiDID {
  static fromJSON(jsonValue: any): NapiDID
}
