name: 'publish-rust'
description: 'Publishes Rust library to crates.io'
inputs:
  crates-token:
    description: 'used for authenticating towards crates.io'
    required: true
  version:
    description: 'the version to release under'
    required: true
  dry-run:
    description: 'will not publish of set, but only log the potential result'
    required: false
runs:
  using: "composite"
  steps:
    - name: Install Rust stable toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        override: true

    - name: Install cargo-workspaces
      uses: actions-rs/cargo@v1
      with:
        command: install
        args: cargo-release

    - name: Publish library to crates.io
      shell: sh
      # add to non-dry run `--no-confirm`
      run: cargo release --workspace --token ${{ inputs.crates-token }} --isolated --no-dev-version --no-push --no-tag --verbose $(if [ ${{ inputs.dry-run }} != '' ]; then echo --execute; fi) ${{ inputs.version }}
      working-directory: /
