// Copyright 2020-2021 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

import { Client, Config, VerifiablePresentation } from '@iota/identity-wasm';
import { createVC } from './create_vc';

/**
    This example shows how to create a Verifiable Presentation and validate it.
    A Verifiable Presentation is the format in which a (collection of) Verifiable Credential(s) gets shared.
    It is signed by the subject, to prove control over the Verifiable Credential with a nonce or timestamp.

    @param {{network: Network, explorer: ExplorerUrl}} clientConfig
**/
async function createVP(clientConfig) {
    // Create a default client configuration from the parent config network.
    const config = Config.fromNetwork(clientConfig.network);

    // Create a client instance to publish messages to the Tangle.
    const client = Client.fromConfig(config);

    // Creates new identities (See "createVC" example)
    const {alice, signedVc} = await createVC(clientConfig);

    // Create a Verifiable Presentation from the Credential
    const unsignedVp = new VerifiablePresentation(alice.doc, signedVc.toJSON())

    // Sign the presentation with a challenge (usually generated by the requester to mitigate replay attacks).
    const signedVp = alice.doc.signPresentation(unsignedVp, {
        method: "#sign-0",
        private: alice.key.private,
    }, new SignatureOptions({
        "challenge": "016da689-a7fb-492a-ac76-4bf19a17ff36"
    }))

    // Check the validation status of the Verifiable Presentation.
    const result = await client.checkPresentation(signedVp.toString());

    console.log(`VP verification result: ${result.verified}`);
}

export {createVP};
