// Copyright 2020-2022 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

/// Supported types representing a DID that can be generated by the [`Storage`](crate::storage::Storage) interface.
#[derive(Clone, Copy, Debug)]
pub enum DIDType {
  /// Corresponds to [`IotaDID`](identity_iota_core::did::IotaDID).
  IotaDID,
}
