/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export class ExternalObject<T> {
  readonly '': {
    readonly '': unique symbol
    [K: symbol]: T
  }
}
export type JsStronghold = Stronghold
export class Stronghold {
  constructor()
  /** Returns whether save-on-drop is enabled. */
  get dropsave(): boolean
  /**
   * Set whether to save the storage changes on drop.
   * Default: true
   */
  set dropsave(dropsave: boolean)
}
export type JsTest = Test
export class Test {
  constructor(count: number)
  get count(): number
}
