name: 'rust-setup'
description: 'Prepares a rust environment and relevant caches.'
inputs:
  target:
    description: 'Additionally install specified target for this toolchain, ex. x86_64-apple-darwin'
    required: false
  components:
    description: 'Comma-separated string of additional components to install e.g. `clippy`, `rustfmt`'
    required: false
  os:
    description: 'OS of the runner, used for cache key construction.'
    required: true
  job:
    description: 'Name of the job, used for cache key construction.'
    required: true
  target-cache-enabled:
    description: 'Cache build artifacts from the target path. Default: false.'
    required: false
    default: ''
  target-cache-path:
    description: 'Path of the target cache.'
    required: false
    default: target
  sccache-enabled:
    description: 'Install and use sccache. Default: false.'
    required: false
    default: ''
  sccache-path:
    description: 'The sccache directory. E.g. "/home/runner/.cache/sccache"'
    required: false
runs:
  using: "composite"
  steps:

    - name: Get current date linux / macos
      if: inputs.os == 'macos-latest' || inputs.os == 'ubuntu-latest'
      shell: sh
      run: echo "CURRENT_DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

    - name: Get current date windows
      if: inputs.os == 'windows-latest'
      shell: pwsh
      run: echo "CURRENT_DATE=$(Get-Date -Format "yyyy-MM-dd")" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

    - name: Install stable toolchain
      uses: dtolnay/rust-toolchain@ce8f65846d7180d2ce63b1e74483d981800b9e22
      with:
        toolchain: stable
        targets: ${{ inputs.target }}

    - name: Cache cargo
      uses: actions/cache@v2.1.7
      with:
        # https://doc.rust-lang.org/cargo/guide/cargo-home.html#caching-the-cargo-home-in-ci
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
        # Add date to the cache to keep it up to date
        key: ${{ inputs.os }}-cargo-${{ inputs.job }}-${{ hashFiles('**/Cargo.toml') }}-${{ env.CURRENT_DATE }}
        # Restore from outdated cache for speed
        restore-keys: |
          ${{ inputs.os }}-cargo-${{ inputs.job }}-${{ hashFiles('**/Cargo.toml') }}-
          ${{ inputs.os }}-cargo-${{ inputs.job }}-
          ${{ inputs.os }}-cargo-

    # Generate Cargo.lock files for build, sccache cache keys.
    # Allows dependencies updated on crates.io between runs to trigger storing an updated cache,
    # which hashing Cargo.toml files alone does not.
    - name: Cargo update
      run: cargo update 

      uses: actions-rs/cargo@v1
      with:
        command: update

    - name: Cache build target
      uses: actions/cache@v2.1.7
      if: inputs.target-cache-enabled == 'true'
      with:
        path: ${{ inputs.target-cache-path }}
        # Add date to the cache to keep it up to date
        key: ${{ inputs.os }}-target-${{ inputs.job }}-${{ hashFiles('**/Cargo.lock') }}
        # Restore from outdated cache for speed
        restore-keys: |
          ${{ inputs.os }}-target-${{ inputs.job }}-
          ${{ inputs.os }}-target-

    - name: Cache sccache
      uses: actions/cache@v2.1.7
      if: inputs.sccache-enabled == 'true'
      with:
          path: ${{ inputs.sccache-path }}
          key: ${{ inputs.os }}-sccache-${{ inputs.job }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ inputs.os }}-sccache-${{ inputs.job }}-
            ${{ inputs.os }}-sccache-