/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

module.exports = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually

  docs: [
    'intro',
    'intro_ssi',
    {
      type: 'category',
      label: 'Getting Started',
      collapsed: false,
      items: [
        'getting-started/overview',
        {
          'Decentralized Identifiers (DID)': [
            'getting-started/did/README',
            'getting-started/did/create',
            'getting-started/did/resolve',
            'getting-started/did/update',
            'getting-started/did/merkle_key_collection',
          ],
        },
        {
          'Verifiable Credentials': [
            'getting-started/vc/README',
            'getting-started/vc/create',
            'getting-started/vc/revoke',
            'getting-started/vc/vp',
          ]  
        },
        {
          'DID Communication': [
            'getting-started/didcomm/README',
            'getting-started/didcomm/did_comm_messages',
            'getting-started/didcomm/protocols',
          ],
          'Advanced Concepts':[
            'getting-started/advanced/README',
            'getting-started/advanced/client',
            'getting-started/advanced/did_messages',
            'getting-started/advanced/storage_adapter',
            'getting-started/advanced/signature_schemes',

          ]  
        },
      ],
    },
    {
      type: 'category',
      label: 'Programming Languages',
      collapsed: true,
      items: [
        {
          type: 'category',
          label: 'Rust',
          collapsed: true,
          items: [
            'libraries/rust/README',
            'libraries/rust/getting_started',
            'libraries/rust/examples',
            'libraries/rust/api_reference',
            'libraries/rust/troubleshooting',
          ],
          
        },
        {
          type: 'category',
          label: 'WASM',
          collapsed: true,
          items: [
            'libraries/wasm/README',
            'libraries/wasm/getting_started',
            'libraries/wasm/examples',
            'libraries/wasm/api_reference',
            'libraries/wasm/troubleshooting',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Specificatons',
      collapsed: true,
      items: [
        'specs/README',
        'specs/iota_did_method_spec',
        'specs/merkle_key_collection',
      ],
    },
    'glossary',
    'contribute',
    'contact',
    'faq'
  ],
};
