name: Wasm Create Hotfix PR

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Name of the support branch (e.g. `support/wasm-v1.2`)'
        required: true

jobs:
  create-hotfix-pr:
    uses: './.github/workflows/shared-create-hotfix-pr.yml'
    with:
      branch: ${{ github.event.inputs.branch }}
      branch-regex: ^support\/wasm-v[0-9]+\.[0-9]+$
      tag-prefix: wasm-v
      main-tag-regex: ^wasm-v[0-9]+\.[0-9]+\.[0-9]+$
      changelog-config-path: ./bindings/wasm/identity_wasm/.github_changelog_generator
      changelog-path: ./bindings/wasm/identity_wasm/CHANGELOG.md
      release-target: wasm
    secrets:
      GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
      GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
